### ISSUE TITLE
Auto Play Music Sheets doesn't work anymore!

### ISSUE THREAD

**Issue by NobushiZoey** [XeTrinityz/ThatSkyMod#1]
I think the instrument Player update kinda broke it. Thats pretty much it, much love <3

**Comment by XeTrinityz** [comment]
Works perfectly fine for me. Any issues you are having must be from the music sheet itself or you did not check the "IMPORTANT" tooltip.

**Comment by NobushiZoey** [comment]
i sended that message before you posted the 3.2.0, Thanks anyway <3

Keep the good work, you are the best!!
