### ISSUE TITLE
About version 3.8.0 update read.me file 

### ISSUE THREAD

**Issue by babamioldurdum** [XeTrinityz/ThatSkyMod#4]
I couldn't find any information on how to update read.me for the 3.8.0 update and I don't know anything about this kind of work; I'm so sorry, I'm literally like a moth to this type things. Can you please explain this to me like you would to a monkey? Thank you so much for your interest and everything <3

**Comment by XeTrinityz** [comment]
You should join the Discord server for support.

https://discord.gg/thatskymod
